# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: deploy-shiny-app

jobs:
  deploy-shiny-app:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v1

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rsconnect
            markdown

      - name: Install precisely
        run: |
          install.packages("remotes")
          remotes::install_github("malcolmbarrett/precisely")
        shell: Rscript {0}

      - name: Authorize and deploy app
        env:
          RSCONNECT_USER: ${{ secrets.RSCONNECT_USER }}
          RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
          RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
        run: |
          rsconnect::setAccountInfo(Sys.getenv("RSCONNECT_USER"), Sys.getenv("RSCONNECT_TOKEN"), Sys.getenv("RSCONNECT_SECRET"))
          rsconnect::deployApp(appDir = "inst/shiny_app/precisely", appId = "528780", forceUpdate = TRUE)
        shell: Rscript {0}
